name: Fetch CWB Weather

on:
  schedule:
    # 每 6 小時抓一次
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # ➊ 這裡把 Secrets 帶進來
    env:
      CWB_API_KEY: ${{ secrets.CWB_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests            # ➋ 安裝 requests
        run: pip install requests

      - name: Run fetch script
        run: python scripts/fetch_cwb_weather.py

      - name: Commit & push
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "auto-bot"
          git add quiz/weather_live.json
          git commit -m "chore: update CWB weather" || echo "no change"
          git push
