name: fetch-7day-forecast        # Workflow 名稱，可自行修改

on:
  schedule:
    - cron: "0 */6 * * *"        # 每 6 小時 (UTC)；台灣時間 08:00‧14:00‧20:00‧02:00
  workflow_dispatch:             # 允許手動觸發

permissions:
  contents: write                # 允許自動 Commit JSON

env:                              # ← 放在 jobs 之外也可以，整隻流程都讀得到
  CWB_API_KEY: ${{ secrets.CWB_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch 7-day forecast
        run: python scripts/fetch_forecast_weather.py   # ← 檔名與 repo 保持一致

      - name: Commit & push
        run: |
          git config user.name  "AutoForecastBot"
          git config user.email "bot@github.com"
          git add quiz/forecast_weather.json
          git commit -m "ci: update 7-day forecast $(date -u '+%Y-%m-%d %H:%M')"
          git push
