name: Fetch CWB Weather

on:
  workflow_dispatch: {}      # 手動觸發保留
  schedule:                  # 自動排程
    - cron: '*/5 * * * *'    # 每 6 小時的整點執行一次
          # 分 時 日 月 星期  (cron 語法)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CWB_API_KEY: ${{ secrets.CWB_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run fetch script
        run: python scripts/fetch_cwb_weather.py

      - name: Commit & push
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "auto-bot"
          git add quiz/weather_live.json
          git commit -m "chore: update CWB weather" || echo "no change"
          git push
