name: Fetch CWB Weather

on:
  schedule:
    # 每小時整點跑一次；之後再視需求調整
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run fetch script
        run: python scripts/fetch_cwb_weather.py

      - name: Commit & push
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name  "auto-bot"
          git add quiz/weather_live.json
          git commit -m "chore: update CWB weather" || echo "no change"
          git push
