name: Fetch CWB Weather

on:
  workflow_dispatch: {}          # 手動觸發，保留
  schedule:                      # 自動排程       
    #       分  時 日 月 星期
    - cron: "0 */6 * * *"

permissions:
  contents: write                # 允許把變更 push 回 repo

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CWB_API_KEY: ${{ secrets.CWB_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python scripts/fetch_cwb_weather.py

      - name: Commit & push updated JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet quiz/weather_live.json; then
            echo "No changes in weather_live.json"
          else
            git add quiz/weather_live.json
            git commit -m "chore: update weather_live.json ($(date -u +'%Y-%m-%dT%H:%MZ'))"
            git push origin HEAD:main
          fi
