name: auto-update-quiz

on:
  workflow_dispatch:
    # 這樣你就可以手動點「Run workflow」來執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pdfplumber pandas

      - name: fetch & convert
        run: python scripts/parse_quiz.py

      - name: Commit updated quiz
        run: |
          git config user.name "AutoUpdate"
          git config user.email "auto@users.noreply.github.com"
          git add quiz/*.pdf quiz/*.json
          git diff --quiet || git commit -m "auto-update quiz $(date +'%Y')" 
          git push
