permissions:
  contents: write

name: auto-update-quiz

on:
  workflow_dispatch:    # 手動觸發
  schedule:
    - cron: "0 2 * * *" # 每天台北時間 10:00（UTC02:00）自動跑

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Parse Excel to JSON
        run: python scripts/parse_excel.py

      - name: Commit parsed JSON
        run: |
          git config user.name "AutoUpdate"
          git config user.email "auto@github.com"
          git add quiz/quiz_114_parsed.json
          git diff --cached --quiet || git commit -m "自動解析 701 筆題庫"
          git push
