# .github/workflows/update_quiz.yml
name: auto-update-quiz
on:
  #schedule:            # 每年 1 月 10 日 00:30 台灣時間
    #- cron: '30 16 1 * *'   # GitHub 用 UTC；16:30=+8h→00:30
  workflow_dispatch:   # 允許手動觸發
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4+

      - name: Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ← 這裡開始
      - name: Install dependencies
        run: |
          pip install pdfplumber pandas requests beautifulsoup4 lxml
      # ← 安裝好後才跑下方的腳本

      - name: fetch & convert
        run: python scripts/fetch_quiz.py

      - name: commit
        run: |
          git config user.name  "AutoUpdate"
          git config user.email "auto@users.noreply.github.com"
          git add quiz/*.json quiz/*.pdf
          git commit -m "auto: update quiz $(date +'%Y')" || echo "no change"
          git push
